idf_component_register(
    SRCS
        "main.c"
        "protocol_frames.c"
        "audio_ring_buffer.c"
        "energy_detector.c"
        "kws_engine.c"
        "i2s_mic.c"
        "ws_client.c"
        "wifi_connect.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_driver_i2s
        esp_websocket_client
        esp_wifi
        nvs_flash
        esp_event
        esp_netif
        freertos
        mbedtls
)
